# For official documentation on this workflow, please refer to the link below.
# https://github.com/brandwatch/bw-workflow-actions/blob/dev/workflows/debian/debian-package-deliver.yaml.md

name: CI Pipeline - Build and Deliver Debian Package

permissions:
  checks: write
  contents: read

on:
  push:
    branches:
      - "main"

jobs:
  deploy-debian-pipeline:
    name: "Build and Deliver Debian Package"
    uses: brandwatch/bw-workflow-actions/.github/workflows/debian-build-deliver-package.yaml@dev
    with:
      package-file: package.deb
      package-folder:
      # prefix is usually first letter of vendor, package-name does not include metadata, but artifact-name does
      # see http://ftp.debian.org/debian/pool/ for examples on structuring debian packages
      artifactory-directory-and-file: pool/<prefix>/<package-name>/<artifact-name>.deb
      deb-distributions:
      deb-components:
      deb-architectures:
    secrets: inherit
