# For official documentation on this workflow, please refer to the link below.
# https://github.com/brandwatch/bw-workflow-actions/blob/dev/workflows/debian/debian-package-deliver.yaml.md

name: CI Pipeline - Build and Deliver Debian Package

permissions:
  checks: write
  contents: write
  packages: read

on:
  release:
    types: [ released ] # can be `published` to run on pre-release instead of production releases

jobs:
  deploy-debian-pipeline:
    name: "Build and Deliver Debian Package"
    uses: brandwatch/bw-workflow-actions/.github/workflows/debian-build-deliver-package.yaml@dev
    with:
      package-version: ${{ github.ref_name }}
      package-folder: # Location of the folder which contains the DEBIAN subfolder
      deb-distributions:
      deb-components:
      deb-architectures:
    secrets: inherit
