# For official documentation on this workflow, please refer to the link below.
# https://github.com/brandwatch/bw-workflow-actions/blob/dev/workflows/java/java-maven-pull-request.yaml.md

name: CI Pipeline - Pull Requests

permissions:
  checks: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - $default-branch

jobs:
  pr-pipeline:
    name: "PR Pipeline"
    uses: brandwatch/bw-workflow-actions/.github/workflows/java-maven-pull-request.yaml@production
    with:
      jvm-version: 17    # Please update with the JVM version of your project
    secrets: inherit
