name: CI Pipeline - Build Image

permissions:
  checks: write
  contents: read

on:
  push:
    branches:
      - $default-branch

jobs:
  build-pipeline:
    name: "Build Pipeline"
    uses: brandwatch/bw-workflow-actions/.github/workflows/java-maven-build-deploy-image.yaml@production
    with:
      jvm-version: 17
    secrets: inherit
