# For official documentation on this workflow, please refer to the link below.
# https://github.com/brandwatch/bw-workflow-actions/blob/dev/workflows/node/node-deploy-package.yaml.md

name: CI Pipeline - Publish Package

permissions:
  checks: write
  contents: write
  security-events: write
  actions: read

on:
  release:
    types: [ released ] # can be `published` to run on pre-release instead of production releases

jobs:
  build-pipeline:
    name: "Publish"
    uses: brandwatch/bw-workflow-actions/.github/workflows/node-deploy-package.yaml@production
    with:
      version: ${{ github.ref_name }}
      node-version: 18 # Can be 18, 20, or 22
      build-step: false # Do you run build before packaging? If so, then set this to true
      linter: false # optional, will run "npm run lint". Set to false if you do not have a lint configuration
      test: true # optional, will run "npm test". Set to false if you do not have a test suite yet
    secrets: inherit
