name: CI Pipeline - Build Image

permissions:
  checks: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-pipeline:
    name: "Build Pipeline"
    uses: brandwatch/bw-workflow-actions/.github/workflows/node-build-deploy-image.yaml@production
    with:
      node-version: 18 # Can be 16 or 18
      package-manager: npm # Can be yarn or npm
      linter: true # optional, will run "npm run lint". Set to false if you do not have a lint configuration
      test: true # optional, will run "npm test". Set to false if you do not have a test suite yet
      build-step: false # optional, can be true if your NodeJS project is built before running
    secrets: inherit
